### ISSUE TITLE
Extruder works in wrong direction

### ISSUE THREAD

**Issue by MULAWI** [TinkerGnome/Ultimaker2Marlin#118]
Hi guys
my extruder feed in wrong direction... on original Marlin I was able to tweak that but on this build, couldn?t find the right line. Can someone give a hand? Thanks!

Printer UM2 upgraded to 2+

**Comment by gr5** [comment]
You can control this on the control panel.  You don't need to change any lines of code.  It's somewhere in the menu system - you can toggle the direction for any of the 5 steppers.  Let me know if you can't find it and I'll turn on my UM2 but I think it's in "motion control" or something like that.

Of course you can't do this in the standard Ultimaker Marlin firmware.  You need this version that we are looking at now.  TinkerGnome/Ultimaker2Marlin.

**Comment by foreachthing** [comment]
Just for the record:
START; ADVANCED :arrow_right: Preferences :arrow_right: Motion settings :arrow_right: Invert Axis

**Comment by MULAWI** [comment]
Great, thank you guys... I was able to change it via Control Panel of the Printer. Works great now
