### ISSUE TITLE
Preferences -> Temperature Control menu buggy

### ISSUE THREAD

**Issue by Alex9779** [TinkerGnome/Ultimaker2Marlin#12]
Hi TG,
I recently went through the preferences and tried to access the Temperature control menu. When I click the menu entry nothing happens. It seems I am in the menu but do not see any changes. When I click the button again I am back in the preferences menu and can move the cursor again there. When I make a scroll with the wheel for about one or two ticks and click then again I seen the settings in the menu. Then the back button do not bring me back to the preferences menu, I see still the temperature control menu.
Seems there is some bug in the menu bathing there...

Regards,
Alexander

**Comment by TinkerGnome** [comment]
ooops, thanks for testing the single extruder version... :smile: 
I'll take a look at it.

**Comment by TinkerGnome** [comment]
This should be fixed with [V15.12](https://github.com/TinkerGnome/Ultimaker2Marlin/releases/tag/V15.12)

**Comment by Alex9779** [comment]
Will check that too... You are the best...

**Comment by Alex9779** [comment]
Works :)...
