### ISSUE TITLE
its about imr to make the code public! would you??

### ISSUE THREAD

**Issue by 369Martin369** [TinkerGnome/Ultimaker2Marlin#123]
Would you be so kind to teach how you made this historic hit piece by showing us the raw code so that we can port it all kinds of other displays?? Thanks

**Comment by gr5** [comment]
All the code is already public.  I'm not sure what you are asking.  github is a webiste for publishing and collaborating on code.  That's the main purpose of github (sharing open source code).  Not the only purpose but the main purpose.

Google about how to use github, how to download the repository, see the changes (so you can see only the changes made in this version/fork of marlin for example and don't have to look at all of marlin).

There are very simple to use tools to help you look at just the changes in this fork.  With comments about the changes, who made the changes, when, etc.
