### ISSUE TITLE
Parameterize two fixed values ...

### ISSUE THREAD

**Issue by gpb01** [TinkerGnome/Ultimaker2Marlin#15]
Hi Tinkergnome,
I report here what I already asked on the UM forum ... :-)

... Is it possible to add two parameters (maybe) in Advanced -> Preferences -> Motion Settings -> _unload/load speed_ ...

The two parameters should allow to set, by the Menu, the two values currently fixed by these two constants in the firmware (file ULTI_LCD2_MENU_MATERIAL_H):
# define FILAMENT_REVERSAL_SPEED

...
# define FILAMENT_INSERT_FAST_SPEED

The reason for this request is to make it easier to use third party extruders that, often, requires different values (_e.g. BondTech QR Extruder_) without the need to re-compile the firmware. 

Thanks in advance,

Guglielmo

**Comment by TinkerGnome** [comment]
With the [latest release](https://github.com/TinkerGnome/Ultimaker2Marlin/releases/tag/V16.03) the filament change speed  depends on the steps/mm of the feeder. This should work with a wide range of feeders. If you like, test it out.

**Comment by gpb01** [comment]
Hi TinkerGnome,
thanks a lot, as soon as possible I will test ;-)
