### ISSUE TITLE
Temperature overshot when starting cold extruder

### ISSUE THREAD

**Issue by Fraeser** [TinkerGnome/Ultimaker2Marlin#20]
There is an variable called "PID_FUNCTIONAL_RANGE "

IT is set to 1000, shouldn't be higher then 20.

If it is set too high you have massive temperature overshot when heating cold or inactive extruder.
Because of the big delay from starting the heater to its final temperature you get in PID calculation an huge I-value.
Thats responsible for temp overshot.

**Comment by TinkerGnome** [comment]
I'm pretty sure, that i never touched this value - but it's a good point. I'll take a look at it, thanks!

**Comment by TinkerGnome** [comment]
Hi Fraeser,
i made some experiments - a value of 15 seems to be a good range for the Ultimaker hotend. The overshot is reduced to 1-2 degrees. Huge improvement!
You should repeat your report at the [Ultimaker master repository](https://github.com/Ultimaker/Ultimaker2Marlin)
