### ISSUE TITLE
ultimaker2go heated bed suppport

### ISSUE THREAD

**Issue by ARKopp** [TinkerGnome/Ultimaker2Marlin#21]
is there already the feature that you have a heated bed in the firmware?

**Comment by TinkerGnome** [comment]
AFAIK, George made a version for the 3DSolex heated bed, you should contact him for details.
Here is the link: http://gr5.org/hb/

**Comment by ARKopp** [comment]
ok thanks I already got that one. I thought yours was different.

**Comment by TinkerGnome** [comment]
I added a variant for the UM2go with heated bed. I don't own this model, would you give it a try and report any issues here?
Here is the [release](https://github.com/TinkerGnome/Ultimaker2Marlin/releases/tag/V16.03).

**Comment by ARKopp** [comment]
works great! just checket it.

**Comment by ARKopp** [comment]
no issues so far with it.

**Comment by ARKopp** [comment]
now I got an issue. When I changed the material then you get out of the menu. then the print is still printing and I am in the inital menu.

**Comment by ARKopp** [comment]
also when changing the material it starts again and then pushes material for priming out right on top not on the side before starting again.

**Comment by ARKopp** [comment]
ok after changing the material the menue switches in the menue from the beginning to stop the print you have to turn off the printer.

**Comment by TinkerGnome** [comment]
Yep, you're right - the pause menu is broken with this version. This applies to all variants...
I'll fix it in the next days - if i find some time...

**Comment by ARKopp** [comment]
Hi,

do you have the firmware on github as well so I could do some adjustments
there?

thanks

Andreas

**Comment by TinkerGnome** [comment]
It's the normal branch [geek_UM2go](https://github.com/TinkerGnome/Ultimaker2Marlin/tree/geek_UM2go), compiled with these defines:
`TEMP_SENSOR_1=0`
`TEMP_SENSOR_BED=20`
`EXTRUDERS=1`
`FILAMENT_SENSOR_PIN=30`
`BABYSTEPPING`
`HEATER_0_MAXTEMP=275`
`HEATER_1_MAXTEMP=275`
`HEATER_2_MAXTEMP=275`

**Comment by ARKopp** [comment]
ok cool thanks. somethime in the future I will do it myself.

Did you have time to fix the stop error?

**Comment by TinkerGnome** [comment]
The menu order (for the pause menu) should be fixed now. Regarding the material change (mid print) - i hope it works as before, but i had not enough time to make tests.
