### ISSUE TITLE
Resume at wrong position?

### ISSUE THREAD

**Issue by Blizzke** [TinkerGnome/Ultimaker2Marlin#28]
On my UM2+ (TG v16.03.1) simply pausing and then resuming apparently restarts printing at the wrong position.
Can't measure it exactly, but it seems to start 5mm more towards the front of the printer and 5mm more towards the right (side of the knob). 

![img_20160420_153122](https://cloud.githubusercontent.com/assets/231572/14676577/5c742602-070e-11e6-9f2b-546a7a499800.jpg)
Orientation of the print was with the left side of the picture to the front of the printer.

Changed the filament manually: paused, changed filament, resume with the result above.

The time before I used the change material function but somehow that one lowered the Z twice and never raised it again and resumed printing in the air afterwards.

**Comment by TinkerGnome** [comment]
good point - i rarely use the pause function and never the change material wizard. There's a good chance that i didn't noticed a problem there (yet)... ;-)

**Comment by TinkerGnome** [comment]
wait a minute... how did you triggered the pause? With the menu on the printer or via gcode (which gcode?). And was it a print from sdcard or via usb? Each way is different...

**Comment by Blizzke** [comment]
Nope nope, a regular ol' pause via the printer menu (same for the change material). Printing from SD.

**Comment by JUSTDO1** [comment]
HI there,
It happens for me as well. i own um2 extendend and the pause (in the printer menu) makes the same problem as shown Blizzke.
Thanks so much for developing this. :+1:

**Comment by arduware** [comment]
Hello, with me as well.
When I press pause on the printer, the pressure is continued added.
but does not occur directly after a restart of the printer.

**Comment by armin-fx** [comment]
Hello,
I think that is the same cause:
I press pause on the printer.
After the printer is paused I press abort, the printer make strange things.
The head will move anywhere like the print goes on on a different position.

**Comment by TinkerGnome** [comment]
It's hard to reproduce, because it does not happen every time.
I tried a fix and made a dozen attepts (with success). Can anyone try it with [this release](https://github.com/TinkerGnome/Ultimaker2Marlin/releases/tag/V16.07) to confirm a difference...?
