### ISSUE TITLE
Download hex and self build differ significantly 

### ISSUE THREAD

**Issue by derbroti** [TinkerGnome/Ultimaker2Marlin#29]
Probably just my fault but why does my build hex file differ by 10469 lines - so not just some minor build config things. [also looking at the disassembles show several differences]

I downloaded the provided zip in the release  https://github.com/TinkerGnome/Ultimaker2Marlin/archive/V16.03.1.zip
then build my own with the proviced package.sh script and compare to the also provided *.hex the files are different.

Where is the problem? Do you have to use specific arduino library versions? 
I tried to build with arduino 1.6.6 on a mac and 1.6.8 on ubuntu.

**Comment by TinkerGnome** [comment]
as long as it works, i wouldn't care...
The hex-files here are compiled with Arduino 1.6.5. on a 32bit Windows7.

**Comment by derbroti** [comment]
In principle you are right "as long as it works" but how do I know? - without having to risk encountering a bug in a multi-hour/day print when I am not staring at my printer -  having different binaries means different potential bugs - which worries me because then people might encounter problems that everyone else can not reproduce because their build system produced different binaries. 

A self build 1.6.5 now finally .... got me a build that has only 28 bytes of differences.
I can work with that - but honesty I am still uneasy with the build process - even the official UM2 marlin firmware has a "Configuring and compilation:" section that is beyond outdated...

**Update:**
I checked, and indeed the only diffs are now in the strings, specific in the build date.

So generally, if it is not too much of a hassle: can you include in future releases the version of the arduino  IDE that you were using? :) (the OS luckily does not matter)
