### ISSUE TITLE
Unable to cancel Change Material

### ISSUE THREAD

**Issue by EldRick** [TinkerGnome/Ultimaker2Marlin#3]
Using your 15.03, I find that if I start the UM2 from Power-On with filament inserted, then select Material / Change, and wait for the nozzle to heat and the filament to retract, the CANCEL choice is not functional.

**Comment by TinkerGnome** [comment]
Fixed with [V15.03.1](https://github.com/TinkerGnome/Ultimaker2Marlin/releases)
Thank you for testing!
