### ISSUE TITLE
Preset temperature not showing.

### ISSUE THREAD

**Issue by GraemeCraig** [TinkerGnome/Ultimaker2Marlin#34]
SInce updating my material list the preset nozzle temperature is not showing on the LCD screen during warmup of the nozzle and table on my UM2 but the heated bed is.
Is this a bug or is there something wrong in my material file

Thanks
Graeme

**Comment by TinkerGnome** [comment]
Is this issue still persistent?
Can you export the material settings to the sdcard and compare the file with your version?

**Comment by GraemeCraig** [comment]
It turns out the preset temperature only shows after the heated bed is up to temperature.
It's not a bug really I suppose, Its just a bit annoying when it doesn't appear, something I live with.

Thanks for the reply though.
