### ISSUE TITLE
Tinker V16.07 - Buildplate rises after faild print

### ISSUE THREAD

**Issue by digifiel** [TinkerGnome/Ultimaker2Marlin#38]
With tinker 16.07 and a UM2+ after canceling a print the build plate goes complete up instead of down.
this causes the heatedbed to crash into the extruder.

**Comment by TinkerGnome** [comment]
I made some tests and noticed, that a direct abort from the printing screen works, but if you try to abort a print, that is already in pause state, still strange things happen...
Can you confirm this?

**Comment by digifiel** [comment]
I'll try to flash back the firmware this afternoon and will do some testing.
Can't remeber if it happend after a manual abort or with the tunell sensor.

**Comment by digifiel** [comment]
Had some spare time this morning so tested it already.

Direct abort without any problems, abort from tunell sensor or pause will cause the buildplate to crash into the extruder.

**Comment by TinkerGnome** [comment]
Hi digifiel,
i hope i found the reason - aborting from the paused state seems to work now.
I you want, give it another try with [V16.08](https://github.com/TinkerGnome/Ultimaker2Marlin/releases/tag/V16.08.1)

**Comment by ieol** [comment]
Hi, 
V16.08 aborting while the printer is running on the first layer still cause the build plate to get pushed towards the print head and the feeder motor run forward fast for a second or two then goes backward longer than the settings (for me settings is 3mm the filament goes backward about 15mm! )

Regards

p.s.: Ver.16.03.1 still the best choice (for me) and a nice firmware  ;)

**Comment by digifiel** [comment]
No problems resuming after a pause by the tunell sensor, also it looks that the material flow is better now.

Will test it this week and if i get any strange errors i will let you know.

Update: 30/08
Still get some problems after aborting, also with the retraction as mentioned in above post.

Will try to replicate the problems tomorrow.

**Comment by digifiel** [comment]
Had some spare time at work this afternoon.

firstlayer pause -> abort will cause the printbed to move down and then complete up again.

Also after flashing the firmware and level the printbed will cause smashing the bed to the extruder.
if you switch of and on there is no problem, so normaly there is no problem but forgot to reboot after the flash.

**Comment by TinkerGnome** [comment]
Bug fixed with revised version 16.08.2
