### ISSUE TITLE
error stopped heater error when setting full power timeout to 120 seconds

### ISSUE THREAD

**Issue by RobotToaster** [TinkerGnome/Ultimaker2Marlin#40]
Using 16.08.2 for UM2+
In heater preferences I set timeout to 30 mins and max power timeout to 120 seconds and stored it.
Now when I open "move" in main menu within seconds a error stopped heater error appears.

**Comment by TinkerGnome** [comment]
Nice find. Probably there's an integer overflow somewhere...

**Comment by TinkerGnome** [comment]
Fixed in V16.12.
