### ISSUE TITLE
New feeder is in reverse, old one is running correctly

### ISSUE THREAD

**Issue by SubZero1993** [TinkerGnome/Ultimaker2Marlin#41]
Hi,

after the upgrade from Ultimaker 2 to Ultimaker 2+ we got a new extrusion feeder, we have built in the old one as the second feeder for the second nozzle. With the latest (Tinker-MarlinUltimaker2-dual-16.08.2) firmware there is the problem that the old feeder ist turning the right way (feeding PLA to the nozzle), but the new shipped feeder is turning in reverse. 
So if we want to print with the first nozzle the Ultimaker is removing the material instead of feeding it to the nozzle.

Is there a possibility to add a function like inverting the signal to the two engines/feeders, so if people have different hardware parts, they can activate/switch/invert the proper signal via the menu on the Ultimaker? (Like switching between primary and secondary nozzle).

Guys, I hope you can help me, your firmware is awesome!

**Comment by Turtletrumpet** [comment]
Hello,
this is not a problem of the firmware. My Ultimaker 2 Extended plus runs without reverse with the original feeder! With the Bondtech QR Feeder and the same firmware(Tinker V16.08.2) the filament runs reverse. I changed two pins on ther stepper motor of the bondtech feeder and all works fine.

regards,

trumpet

**Comment by SubZero1993** [comment]
Oh that sounds great!

We thought about that too, but we wasn't sure which of the four pins we should switch.. The two inner ones or the outer ones? 

Kind regards,
SubZero

**Comment by Turtletrumpet** [comment]
Hello,

I don't know, which two of the four cable/pins you have to change, because this is motor dependant.
sry. Please ask the support of ultimaker, they should know that.

regards,

trumpet

**Comment by SubZero1993** [comment]
Hi,
sure no problem, thank you a lot for your advice! 
Kind regards,
SubZero
