### ISSUE TITLE
Manual Temperature Control Below 100 Deg C Not Accurate

### ISSUE THREAD

**Issue by scottdanesi** [TinkerGnome/Ultimaker2Marlin#42]
I was doing a cold pull to clean my nozzle on my UM2+ and when I went to set the temp at 90 deg, it would not go that low.  It stayed up at about 110.  I then set it to 70 deg and it hovered around 90, so I was able to proceed.  This happens on both the custom nozzle temp menu and the move material menu.

**Comment by scottdanesi** [comment]
All higher temps are accurate.

**Comment by TinkerGnome** [comment]
This is related to the PID settings. Try
Kp = 12.00
Ki = 0.75
Kd = 55.00
That works well for me.

**Comment by scottdanesi** [comment]
That did the trick.  Thank you.  Should these settings be the default when loading the new firmware?

**Comment by TinkerGnome** [comment]
Well, the PID settings are stored in EEPROM and would only change on a factory reset. But you're right, i can place separate defaults for the plus models (with Olsson block), just in case...
It's noted.

**Comment by scottdanesi** [comment]
Excellent.
