### ISSUE TITLE
17.02 dev 

### ISSUE THREAD

**Issue by qwerty8224** [TinkerGnome/Ultimaker2Marlin#61]
does not work UltiGcode 
Cura 2.4 Beta2

**Comment by gr5** [comment]
I was able to print an ultigcode print last night with 17.02 no problem.  But I had sliced it cura 15.X.

What was the symptom exactly?

**Comment by qwerty8224** [comment]
Heated bed nozzle. But printing does not start
Reprep/Marlin  working
Later, I can check on the 15.X
Which mode is better Reprap or Ultigcode?

**Comment by gr5** [comment]
Are you printing through usb or using the SD card?  From SD card use ultigcode.  If printing through USB (which isn't officially supported but works usually) then use reprap mode.

**Comment by qwerty8224** [comment]
From SD card use ultigcode
15.04 not working UltiGcode
probably a problem with me?

**Comment by TinkerGnome** [comment]
Hi @qwerty8224,
how have you compiled your version, and for which printer?
Perhaps some of the compiler defines from package.sh are important?

**Comment by qwerty8224** [comment]
Arduino ide 1.6.6
Ultimaker 2
2 extrusion runs through ultigcode Cura 2.3.1

**Comment by qwerty8224** [comment]
17.02.1 very good )
