### ISSUE TITLE
Cura 15.04 17.02.1

### ISSUE THREAD

**Issue by qwerty8224** [TinkerGnome/Ultimaker2Marlin#63]
Cura 15.04 stopped working UltiGcode (((

Reprap at the beginning of the press got an error Print of area when lifting bed

**Comment by EldRick** [comment]
I was able to run an 18-hour print on UM2 with a zillion retractions with 17.02.1 without the Error - Stopped.

**Comment by qwerty8224** [comment]
Do you work UltiGcode?
Error I think it was an accident.

**Comment by EldRick** [comment]
Yes - I did not set to RepRap.

**Comment by qwerty8224** [comment]
Thank you )
