### ISSUE TITLE
'target_temperature_bed' was not declared in this scope

### ISSUE THREAD

**Issue by nbasse** [TinkerGnome/Ultimaker2Marlin#69]
When setting TEMP_SENSOR_BED  to 0 to disable heated bed, I got error "'target_temperature_bed' was not declared in this scope" when compiling with arduino ide.

To get past this i added an if statement around the lines in temperatures.h that was producing the error.

like this:

`#ifdef BED_MAXTEMP`
`void setTargetBed(const uint16_t &celsius);`
`#else`
`#if TEMP_SENSOR_BED != 0`
`FORCE_INLINE void setTargetBed(const float &celsius)`
`{`
  `target_temperature_bed = celsius;`
`}`
`#endif`
`#endif`

before my edit;

`#ifdef BED_MAXTEMP`
`void setTargetBed(const uint16_t &celsius);`
`#else`
`FORCE_INLINE void setTargetBed(const float &celsius)`
`{`
  `target_temperature_bed = celsius;`
`}`
`#endif`

I'm not sure if i broke something else as I don't complete understand what the affected lines do.

So input from someone who knows this would be good :-)

**Comment by TinkerGnome** [comment]
@nbasse  - thank's for reporting, your fix looks totally fine to me
I transferred your changes into the source repository.
