### ISSUE TITLE
Baby stepping menu: store Z offset

### ISSUE THREAD

**Issue by Alex9779** [TinkerGnome/Ultimaker2Marlin#72]
Hi,
I frequently use the menu for babystepping when starting a print to optimize the Z offset.
This works so far but it seems the option to store the value does not.
If I babystep by +1mm it lowers the build plate, that is fine so far but storing that value adds +1mm to the Z offset which reduces the distance to the nozzle.
After doing so my next print crashed the build plate.
I have to reduce the stored Z offset in EEPROM by the amount I babystepped.
I think the problem is here:
https://github.com/TinkerGnome/Ultimaker2Marlin/blob/geek_mode/Marlin/tinkergnome.cpp#L498
This line has to be:
```
add_homeing[Z_AXIS] -= FLOAT_SETTING(Z_AXIS);
```

**Comment by TinkerGnome** [comment]
right you are... 😃 Thanks!
